config/routes.rb
Rails.application.routes.draw do
  
  root 'cafes#index'
  
  resources :posts  # posts가 아니라 post면 controller에서도 post여야한다.
  post 'posts/:id/comments/create' => 'comments#create' # 댓글을 생성하는 것
  delete 'comments/:id' => 'comments#destroy' # 댓글 삭제하는 것.
  
  # cafe
  resources :cafes, except: [:destroy] # only로 필요한 기능만 뽑아내는 것도 가능
  post '/join_cafe/:cafe_id' => 'cafes#join_cafe', as: 'join_cafe' # as옵션으로 prefix 강제 할당
  
  
    
  
  # authenticate
  get '/sign_up' => 'authenticate#sign_up'
  post '/sign_up' => 'authenticate#user_sign_up'
  get '/sign_in' => 'authenticate#sign_in'
  post '/sign_in' =>'authenticate#user_sign_in'
  delete '/sign_out' => 'authenticate#sign_out'
  get '/user_info/:user_name' => 'authenticate#user_info'
  
end

  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
end

app/models/daum.rb
class Daum < ApplicationRecord
    has_many :memberships
    has_many :users, through: :memberships
    has_many :posts


    # def self.메소드명 -> 클래스 메소드
    #     로직 안에서 self를 쓸 수 없음
    # end
    
    # def 메소드명 -> 인스턴스 메소드
    #     로직 안에서 self를 쓸 수 있음
    #     self == 현재 자신의 객체를 말한다.
    
    # end

    def is_member?(user)
       self.users.include?  user 
    end


end

app/models/membership.rb
class Membership < ApplicationRecord
    belongs_to :user
    belongs_to :daum
end

app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :image_path, ImageUploader # image_path라는 곳에 이미지 주소를 저장할 것이다.
    has_many :comments
    belongs_to :user
    belongs_to :daum
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :user_name, uniqueness: true # 테이블에 이 값이 있으면 에러를 뿜뿜!
    # user_name 칼럼에 unique 속성 부여
    
    has_many :memberships
    has_many :daums, through: :memberships
    has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :user_signed_in?, :current_user
  
  
    def user_signed_in?
        # 현재 유저가 있는지 없는지를 리턴
        session[:sign_in_user].present? # True면 있는거.
    end
  
    def authenticate_user
        redirect_to sign_in_path unless user_signed_in? # 로그인 되어있지 않다면 sign_in 페이지로 가라 (prefix사용)
    end

    def current_user
        @current_user = User.find(session[:sign_in_user]) if user_signed_in? # 유저가 로그인이 되어 있을때만 유저를 검색해줍니다.
    end

end

app/controllers/authenticate_controller.rb
class AuthenticateController < ApplicationController
# 회원가입 페이지
    def sign_up
        @user = User.new
    end
# 실제 회원가입 로직
    def user_sign_up
        @user = User.new(user_name: params[:user_name],
                        password: params[:password],
                        password_confirmation: params[:confirmation])
        if @user.save
            redirect_to root_path, flash: {success: '회원가입 성공'}
        else
            redirect_to :back, flash: {danger: '회원가입 실패'}
        end
    end
# 로그인 페이지
    def sign_in
        
    end
# 실제 로그인 로직
    def user_sign_in
        @user = User.find_by(user_name: params[:user_name])
        
        if @user.present? and @user.authenticate(params[:password])
            session[:sign_in_user] = @user.id
            redirect_to root_path, flash: {success: '로그인 성공'}
        else
            p @users.errors
            redirect_to :back, flash: {danger: '로그인 정보가 잘못 되었습니다.'}
        end
    end

# 유저 정보 페이지
# 로그아웃 로직
    def sign_out
       session.delete(:sign_in_user)
       redirect_to :back, flash: {success: "로그아웃 완료"}
    end
end

app/controllers/cafes_controller.rb
class CafesController < ApplicationController
    
    before_action :authenticate_user, except: [:index,:show] 
    # except안에 있는 메소드를 제외하고 다른 모든 메소드는 실행하기 전에 authenticate_user을 먼저 실행
    
    
    # 전체 카페 목록보여주는 페이지
    # -> 로그인 하지 않았을 때: 전체 카페 목록
    # -> 로그인 했을 때: 유저가 가입한 카페 목록
    
    def index
        if user_signed_in?
            @cafes = current_user.daums
        else
            @cafes = Daum.all
        end
    end
    
    # 카페 내용물을 보여주는 페이지
    def show
        @cafe = Daum.find(params[:id])
        session[:current_cafe] = @cafe.id
    end
    
    # 카페를 개설하는 페이지
    def new
        @cafe = Daum.new
    end
    
    # 카페를 실제로 개설하는 로직
    def create
        @cafe = Daum.new(daum_params)
        @cafe.master_name = current_user.user_name
        if @cafe.save
            Membership.create(user_id: current_user.id, daum_id: @cafe.id)
            redirect_to cafe_path(@cafe), flash: {success: "카페가 개설 되었습니다"}    
        else
            redirect_to :back, flash: {danger: "카페 개설에 실패했습니다."}
        end
    end
    
    # 카페 정보를 실제로 수정하는 로직 - 나중에 시간되면 과제루다가

    # 카페에 가입하는 로직
    def join_cafe
        cafe = Daum.find(params[:cafe_id])
        # 사용자가 가입하려는 카페
        if cafe.is_member?(current_user)
           # 가입 실패
            redirect_to :back, flash: {danger: "카페 가입이 실패되었습니다. 이미 가입된 카페입니다."}
        else
            p @cafe.errors # rollback날때 왜 rollback 났는지 알 수 있는 코드
            
            # 가입 성공 
            # 현재 이 카페에 가입한 유저중에, 지금 로그인한 유저가 있니?
            Membership.create(daum_id: params[:cafe_id], user_id: current_user.id) 
            redirect_to :back, flash: {success: "카페에 가입되었습니다!"}
        end
        # 이 카페에 현재 로그인 된 사용자가 가입이 됐는지?
        
        # 중복 가입을 막을 수 없음
        # 중복 가입을 막는 방법? 
        # 1. 가입버튼을 안보이게 한다. ( 사용자 화면 조작 ) -> Model코딩(method)
        # 2. 중복 가입 체크 후 진행 (서버에서 로직 조작) -> Model validation
         
       
       
    end


    private
    def daum_params
        params.require(:daum).permit(:title, :description)
        # :params => {"daum"=>{"title"=>"test", "description"=>"test"}, "commit"=>"Create_cafe"}}
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.new
    comment.content = params[:content] # 댓글의 내용
    comment.post_id = params[:id] # 댓글의 번호
    comment.save
    
    redirect_to :back
  end

  def destroy
    @comment = Comment.find(params[:id]) # 넘어오는건 comment(댓글)의 id. 사실 삭제할때는 댓글의 아이디만 갖고오면 가능
    @comment.destroy # 찾았으면 삭제
    redirect_to :back
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.daum_id = session[:current_cafe]
      if @post.save
        session.delete(:current_cafe)
        #flash[:notice] = 'Post was successfully created.' 
        redirect_to @post, flash: { success: 'Post was successfully created.' } # 어디로 가는지를 지정, flash의 키를 지정, 그리고 value = notice
      else
        p @post
        render :new 
      end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
      if @post.update(post_params)
        redirect_to @post, flash: { success: 'Post was successfully updated.' }
      else
        render :edit 
      end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
      @post.destroy
      redirect_to posts_url, flash: { success: 'Post was successfully destroyed.' }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :contents, :image_path, {avatars: []}) # 설정해 놓은 파라미터만 받을 수 있습니다. 
      #{title: params[:post][:title], contents: [:post][:title][:daum_id][:image_path]}
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authenticate_helper.rb
module AuthenticateHelper
end

app/helpers/cafes_helper.rb
module CafesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/authenticate/sign_in.html.erb
<h1>log in</h1>
<%=form_tag do %>
    <%= text_field_tag :user_name %><br/>
    <%= password_field_tag :password %><br/>
    <%= submit_tag 'sign_in' %>
<%end%>

app/views/authenticate/sign_up.html.erb
<%=form_tag do %>
    <%= text_field_tag :user_name %><br/>
    <%= password_field_tag :password %><br/>
    <%= password_field_tag :password_confirmation %><br/>
    <%= submit_tag 'sign_up' %>
<%end%>

app/views/cafes/index.html.erb
<h2>다음 카페에 오신 것을 환영합니다.</h2>

<div class="list-group">
    <% @cafes.each do |cafe| %>
    <%= link_to cafe.title, cafe_path(cafe), class: "list-group-item list-group-item-action"%> 
    <% end %>
</div>

<div class = "text-center">
    <%= link_to "카페 개설하기", new_cafe_path, class: "btn btn-success" %>
</div>

app/views/cafes/new.html.erb
<h1>카페 생성하기</h1>
<%= form_for(@cafe, url: cafes_path)do |f| %> <!--순황이 아닌 매칭-->
    <%= f.text_field :title %><br>
    <%= f.text_area :description %><br/>
    <%= f.submit 'Create_cafe' %>
<%end%>

app/views/cafes/show.html.erb
<!--카페 정보 ㄴㄴ -->
<!-- 카페에 등록된 글이 보여야한다. -->
<h1><%= @cafe.title %></h1>
<p><%= @cafe.description %></p>

<%unless @cafe.is_member?(current_user) %>
<!-- 카페 가입버튼 -->
<%= link_to "카페 가입하기", join_cafe_path(@cafe), method: "POST", class: "btn btn-warning text-white"%>
<%end%>

<hr>

<ul class="list-group">
  <% @cafe.posts.each do |post| %>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <%= link_to "#{post.title}", post_path(post) %> <!--path쓰는 방법은 prefix이름_path(가변수) -->

    <span class="badge badge-primary badge-pill"><%= post.comments.count %></span>
  </li>
  <% end %>
</ul>
<hr>
<!-- 새글 등록버튼 -->
<%= link_to "새글 등록", new_post_path(cafe_id: @cafe_id), class: "btn btn-info" %>

app/views/comments/_form.html.erb
<%= form_tag("/posts/#{post.id}/comments/create") do %>
    <!-- 댓글 입력폼 -->
    <%= text_field_tag(:content, nil, class: "form-control", placeholder: "내용을 입력하세요") %>
    <br/>
    <!-- 댓글 작성 -->
    <%= submit_tag("댓글작성", class: "btn btn-primary") %>
    <hr/>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DaumCafe</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">  
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <%flash.each do |k, v|%>
      <div class= "alert alert-<%= k %>"><%= v%></div>
    <%end%>
    <div class ="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(post, html: {class: 'text-center'}) do |f| %>
<%= f.hidden_field :daum_id, value: params[:daum_id] %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :contents %>
    <%= f.text_area :contents, class: 'form-control' %>
  </div>
  
    <div class="field">
    <%= f.label :image_path %>
    <%= f.file_field :image_path, class: 'form-control' %>
  </div>
  <hr>
  <div class="actions">
    <%= f.submit '작성하기',class: 'btn btn-info' %>
    <%= link_to '뒤로 가기', posts_path, class: 'btn btn-warning text-white' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<ul class="list-group">
  <% @posts.each do |post| %>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <%= link_to "#{post.title}", post_path(post) %> <!--path쓰는 방법은 prefix이름_path(가변수) -->

    <span class="badge badge-primary badge-pill"><%= post.comments.count %></span>
  </li>
  <% end %>
</ul>
<hr>
<div>
  <%=link_to 'New Post', new_post_path, class: 'btn btn-info'%>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<h1>
  <strong>Title:</strong>
  <%= @post.title %>
</h1>
<hr>
<p>
  <strong>Contents:</strong>
  <%= @post.contents %>
</p>

<p>
  <strong>ImagePath:</strong>
  <img src ="<%= @post.image_path %>" width="100%"/>
</p>
<p>
  <strong>Thumb Fill:</strong>
  <img src ="<%= @post.image_path.thumb_fill.url %>"/>
</p>
<p>
  <strong>Thumb Fit:</strong>
  <img src ="<%= @post.image_path.thumb_fit.url %>"/>
</p>


<%= link_to '수정', edit_post_path(@post), class: 'btn btn-warning text-white'%> 
<%= link_to '목록', cafe_path(@post.daum), class: 'btn btn-info' %> 
<!--cafe_path(@post.daum)는 @post가 속해있는 카페객체가 하나 튀어나오고, 이것을 매개로 사용하면 cafe_path가 몇번인지 알 수 있다 -->
<%= link_to '삭제', posts_path(@post), method: 'DELETE', class: 'btn btn-danger' %>

<hr>

<!-- 댓글 입력 -->
<%= render 'comments/form', post: @post %>

<!-- 댓글 리스트 -->

<table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Content</th>
      <th scope="col">Button</th>
    </tr>
  </thead>
  <tbody>
    <% @post.comments.each do |comment| %>
    <tr>
      <th scope="row"><%= comment.id %></th>
      <td><%= comment.content %></td>
      <td><%= link_to "삭제", "/comment/#{comment.id}",method: "delete"%></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_footer.html.erb
<footer class="footer">
      <div class="container">
        <span class="text-muted">footer의 자리입니다.</span>
      </div>
     </footer>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="/">Never expand</a>
      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarsExample01" aria-controls="navbarsExample01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="navbar-collapse collapse" id="navbarsExample01" style="">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
          <% unless user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'sign_in', sign_in_path, class: 'nav-link' %>
          </li>
          <% else %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= current_user.user_name %></a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <%= link_to 'Sign_out', sign_out_path, method: 'delete', class: 'dropdown-item', data: {confirm: '로그아웃 하시겠습니까?'} %>
            </div>
          </li>
          <%end%>
        </ul>
        <form class="form-inline my-2 my-md-0">
          <input class="form-control" type="text" placeholder="Search" aria-label="Search">
        </form>
      </div>
    </nav>